package com.magikhelper.dao.pojo;

// Generated Jan 7, 2015 9:17:15 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * BookingService generated by hbm2java
 */
@Entity
@Table(name = "booking_service", catalog = "magikhelper")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class BookingService implements java.io.Serializable {

	private Integer id;
	private ServicesRates servicesRates;
	private Booking booking;
	private Date createTime;
	private Date updateTime;
	private Byte recordStatus;

	public BookingService() {
	}

	public BookingService(ServicesRates servicesRates, Booking booking) {
		this.servicesRates = servicesRates;
		this.booking = booking;
	}

	public BookingService(ServicesRates servicesRates, Booking booking,
			Date createTime, Date updateTime, Byte recordStatus) {
		this.servicesRates = servicesRates;
		this.booking = booking;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.recordStatus = recordStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_rate_id", nullable = false)
	public ServicesRates getServicesRates() {
		return this.servicesRates;
	}

	public void setServicesRates(ServicesRates servicesRates) {
		this.servicesRates = servicesRates;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "booking_id", nullable = false)
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "record_status")
	public Byte getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(Byte recordStatus) {
		this.recordStatus = recordStatus;
	}

}
