package com.magikhelper.dao.pojo;

// Generated Jan 7, 2015 9:17:15 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ServicesRates generated by hbm2java
 */
@Entity
@Table(name = "services_rates", catalog = "magikhelper")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class ServicesRates implements java.io.Serializable {

	private Integer id;
	private Code code;
	private BigDecimal rate;
	private Byte recordStatus;
	private Date updateTime;
	private Date createTime;
	private Set<BookingService> bookingServices = new HashSet<BookingService>(0);

	public ServicesRates() {
	}

	public ServicesRates(Code code, BigDecimal rate) {
		this.code = code;
		this.rate = rate;
	}

	public ServicesRates(Code code, BigDecimal rate, Byte recordStatus,
			Date updateTime, Date createTime,
			Set<BookingService> bookingServices) {
		this.code = code;
		this.rate = rate;
		this.recordStatus = recordStatus;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.bookingServices = bookingServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_id", nullable = false)
	public Code getCode() {
		return this.code;
	}

	public void setCode(Code code) {
		this.code = code;
	}

	@Column(name = "rate", nullable = false, precision = 9)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "record_status")
	public Byte getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(Byte recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicesRates")
	public Set<BookingService> getBookingServices() {
		return this.bookingServices;
	}

	public void setBookingServices(Set<BookingService> bookingServices) {
		this.bookingServices = bookingServices;
	}

}
