package com.magikhelper.dao.pojo;

// Generated Jan 7, 2015 9:17:15 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * VendorSkill generated by hbm2java
 */
@Entity
@Table(name = "vendor_skill", catalog = "magikhelper")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class VendorSkill implements java.io.Serializable {

	private Integer id;
	private Code code;
	private User user;
	private Date createTime;
	private Date updateTime;
	private Byte recordStatus;

	public VendorSkill() {
	}

	public VendorSkill(Code code, User user) {
		this.code = code;
		this.user = user;
	}

	public VendorSkill(Code code, User user, Date createTime, Date updateTime,
			Byte recordStatus) {
		this.code = code;
		this.user = user;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.recordStatus = recordStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "skill_id", nullable = false)
	public Code getCode() {
		return this.code;
	}

	public void setCode(Code code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "record_status")
	public Byte getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(Byte recordStatus) {
		this.recordStatus = recordStatus;
	}

}
